# Generated by Django 2.1.7 on 2019-02-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logEntry', '0002_auto_20190227_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='slug',
        ),
    ]
